codes = {
    "09023": "Retail sale in non-specialized stores",
    "09028": "Retail sale of other products n.e.c",
    "14007": "Other services n.e.c. ",
    "01001": "Growing and manufacturing of tea",
    "01002": "Growing and manufacturing of coffee",
    "01003": "Growing and manufacturing of rubber",
    "01004": "Market gardening and horticulture specialties",
    "01005": "Raising of silk worms and production of silk",
    "01006": "Raising of bees and production of honey",
    "01007": "Raising of poultry and production of eggs",
    "01008": "Rearing of sheep and production of wool",
    "01009": "Rearing of animals and production of animal products",
    "01010": "Agricultural and animal husbandry services",
    "01011": "Soil conservation, soil testing and soil desalination services",
    "01012": "Hunting, trapping and game propagation services",
    "01013": "Growing of timber, plantation, operation of tree nurseries and conserving of forest",
    "01014": "Gathering of tendu leaves",
    "01015": "Gathering of other wild growing materials",
    "01016": "Forestry service activities, timber cruising, afforestation and reforestation",
    "01017": "Logging service activities, transport of logs within the forest",
    "01018": "Other agriculture, animal husbandry or forestry activity n.e.c",
    "02001": "Fishing on commercial basis in inland waters",
    "02002": "Fishing on commercial basis in ocean and coastal areas",
    "02003": "Fish farming",
    "02004": "Gathering of marine materials such as natural pearls, sponges, coral etc.",
    "02005": "Services related to marine and fresh water fisheries, fish hatcheries and fish farms",
    "02006": "Other Fish farming activity n.e.c",
    "03001": "Mining and agglomeration of hard coal",
    "03002": "Mining and agglomeration of lignite",
    "03003": "Extraction and agglomeration of peat",
    "03004": "Extraction of crude petroleum and natural gas",
    "03005": "Service activities incidental to oil and gas extraction excluding surveying",
    "03006": "Mining of uranium and thorium ores",
    "03007": "Mining of iron ores",
    "03008": "Mining of non-ferrous metal ores, except uranium and thorium ores",
    "03009": "Mining of gemstones",
    "03010": "Mining of chemical and fertilizer minerals",
    "03011": "Mining of quarrying of abrasive materials",
    "03012": "Mining of mica, graphite and asbestos",
    "03013": "Quarrying of stones (marble/granite/dolomite), sand and clay",
    "03014": "Other mining and quarrying",
    "03015": "Mining and production of salt",
    "03016": "Other mining and quarrying n.e.c",
    "04001": "Production, processing and preservation of meat and meat products",
    "04002": "Production, processing and preservation of fish and fish products",
    "04003": "Manufacture of vegetable oil, animal oil and fats",
    "04004": "Processing of fruits, vegetables and edible nuts",
    "04005": "Manufacture of dairy products",
    "04006": "Manufacture of sugar",
    "04007": "Manufacture of cocoa, chocolates and sugar confectionery",
    "04008": "Flour milling",
    "04009": "Rice milling",
    "04010": "Dal milling",
    "04011": "Manufacture of other grain mill products",
    "04012": "Manufacture of bakery products",
    "04013": "Manufacture of starch products",
    "04014": "Manufacture of animal feeds",
    "04015": "Manufacture of other food products",
    "04016": "Manufacturing of wines",
    "04017": "Manufacture of beer",
    "04018": "Manufacture of malt liquors",
    "04019": "Distilling and blending of spirits, production of ethyl alcohol",
    "04020": "Manufacture of mineral water",
    "04021": "Manufacture of soft drinks",
    "04022": "Manufacture of other non-alcoholic beverages",
    "04023": "Manufacture of tobacco products",
    "04024": "Manufacture of textiles (other than by handloom)",
    "04025": "Manufacture of textiles using handlooms (khadi)",
    "04026": "Manufacture of carpet, rugs, blankets, shawls etc. (other than by hand)",
    "04027": "Manufacture of carpet, rugs, blankets, shawls etc. by hand",
    "04028": "Manufacture of wearing apparel",
    "04029": "Tanning and dressing of leather",
    "04030": "Manufacture of luggage, handbags and the like saddler and harness",
    "04031": "Manufacture of footwear",
    "04032": "Manufacture of wood and wood products, cork, straw and plaiting material",
    "04033": "Manufacture of paper and paper products",
    "04034": "Publishing, printing and reproduction of recorded media",
    "04035": "Manufacture of coke oven products",
    "04036": "Manufacture of refined petroleum products",
    "04037": "Processing of nuclear fuel",
    "04038": "Manufacture of fertilizers and nitrogen compounds",
    "04039": "Manufacture of plastics in primary forms and of synthetic rubber",
    "04040": "Manufacture of paints, varnishes and similar coatings",
    "04041": "Manufacture of pharmaceuticals, medicinal chemicals and botanical products",
    "04042": "Manufacture of soap and detergents",
    "04043": "Manufacture of other chemical products",
    "04044": "Manufacture of man-made fibers",
    "04045": "Manufacture of rubber products",
    "04046": "Manufacture of plastic products",
    "04047": "Manufacture of glass and glass products",
    "04048": "Manufacture of cement, lime and plaster",
    "04049": "Manufacture of articles of concrete, cement and plaster",
    "04050": "Manufacture of Bricks, Tiles and Construction products in baked clay",
    "04051": "Manufacture of other non-metallic mineral products",
    "04052": "Manufacture of basic iron and steel",
    "04053": "Manufacture of basic precious and non-ferrous metals",
    "04054": "Casting of iron and steel",
    "04055": "Casting of non-ferrous metals",
    "04056": "Manufacture of structural metal products",
    "04057": "Manufacture of tanks, reservoirs and containers of metal",
    "04058": "Manufacture of steam generators, except central heating hot water boilers",
    "04059": "Forging, pressing, stamping and roll-forming of metal",
    "04060": "Treatment and coating of metals; general mechanical engineering on a fee or contract basis",
    "04061": "Manufacture of cutlery, hand tools and general hardware",
    "04062": "Manufacture of other fabricated metal products",
    "04063": "Manufacture of computer, electronic and optical products",
    "04064": "Manufacture of electrical equipment",
    "04065": "Manufacture of domestic appliances",
    "04066": "Manufacture of other machinery",
    "04067": "Manufacture of motor vehicles, trailers and semi-trailers",
    "04068": "Manufacture of other transport equipment",
    "04069": "Manufacture of furniture",
    "04070": "Manufacture of jewelry, bijouterie and related articles",
    "04071": "Manufacture of musical instruments",
    "04072": "Manufacture of sports goods",
    "04073": "Manufacture of toys",
    "04074": "Manufacture of miscellaneous manufacturing articles n.e.c",
    "05001": "Electricity generation, transmission and distribution",
    "05002": "Manufacture of gas, distribution of gaseous fuels through mains",
    "05003": "Steam and hot water supply",
    "06001": "Collection, purification and distribution of water",
    "06002": "Collection and treatment of waste water",
    "06003": "Collection, treatment and disposal of solid waste",
    "06004": "Materials recovery (recycling)",
    "07001": "Site preparation",
    "07002": "Building of complete constructions or parts thereof, civil engineering",
    "07003": "Installation, alteration and demolition of machinery and equipment, other than metal forming machinery",
    "07004": "Plumbing",
    "07005": "Other construction work involving special trades",
    "08001": "Wholesale trade and commission trade, except of motor vehicles and motorcycles",
    "08002": "Retail trade not in stores",
    "08003": "Retail trade in non-specialized stores with food, beverages or tobacco predominating",
    "08004": "Retail trade in specialized stores",
    "08005": "Retail trade of motor vehicle and motorcycle",
    "09001": "Passenger land transport",
    "09002": "Freight land transport",
    "09003": "Transport via pipelines",
    "09004": "Freight air transport",
    "09005": "Passenger air transport",
    "09006": "Space transport",
    "09007": "Operation of railways, rail freight transport",
    "09008": "Operation of railways, passenger rail transport",
    "09009": "Other land transport",
    "09010": "Inland water transport",
    "09011": "Marine transport",
    "09012": "Support activities for transportation",
    "09013": "Cargo handling",
    "09014": "Storage and warehousing",
    "09015": "Service activities incidental to water transportation",
    "10001": "Publishing of books, periodicals and other publishing activities, including integrated publishing",
    "10002": "Publishing of newspapers",
    "10003": "Publishing of journals and periodicals",
    "10004": "Other publishing activity",
    "10005": "Printing",
    "10006": "Service activities related to printing",
    "11001": "Broadcasting of television programme",
    "11002": "Broadcasting of radio programme",
    "11003": "Television programming and broadcasting",
    "11004": "Radio programming and broadcasting",
    "12001": "Wired telecommunications activities",
    "12002": "Wireless telecommunications activities",
    "12003": "Satellite telecommunications activities",
    "12004": "Other telecommunications activities",
    "12005": "Telecommunications reselling",
    "13001": "Internet access services",
    "13002": "Web portals",
    "13003": "Data processing, hosting and related activities",
    "13004": "Other information technology and computer service activities",
    "13005": "Computer programming",
    "13006": "Computer consultancy",
    "13007": "Computer facilities management activities",
    "13008": "Other computer related activities",
    "13009": "Data processing",
    "13010": "Maintenance and repair of office, accounting and computing machinery",
    "13011": "Other software publishing",
    "13012": "Hardware consultancy",
    "13013": "Software consultancy",
    "13014": "Data base activities and distribution of electronic content",
    "13015": "Other Information Technology and Computer Service Activities n.e.c.",
    "14001": "Motion picture, video and television programme production, sound recording and music publishing",
    "14002": "Motion picture, video and television programme post-production activities",
    "14003": "Motion picture, video and television programme distribution activities",
    "14004": "Motion picture projection activities",
    "15001": "Programming and broadcasting of TV, music and radio programmes",
    "15002": "Programming and broadcasting of TV programmes",
    "15003": "Programming and broadcasting of music and radio programmes",
    "16001": "Other telecommunications activities n.e.c",
    "16002": "Other information technology and computer service activities n.e.c",
    "16003": "Motion picture projection activities",
    "16004": "Radio programming and broadcasting",
    "16005": "Television programming and broadcasting",
    "16006": "Sound recording and music publishing activities",
    "16007": "Motion picture, video and television programme distribution activities",
    "16008": "Motion picture, video and television programme post-production activities",
    "16009": "Motion picture, video and television programme production activities",
    "17001": "Manufacture of motor vehicles",
    "17002": "Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semitrailers",
    "17003": "Manufacture of parts and accessories for motor vehicles",
    "18001": "Manufacture of transport equipment",
    "18002": "Manufacture of parts and accessories for transport equipment",
    "19001": "Manufacture of furniture and fixtures",
    "19002": "Manufacture of other fabricated metal products; metal working service activities",
    "19003": "Manufacture of other non-metallic mineral products n.e.c",
    "19004": "Manufacture of sports goods",
    "19005": "Manufacture of office, accounting and computing machinery",
    "19006": "Manufacture of electrical machinery and apparatus n.e.c",
    "19007": "Manufacture of general purpose machinery",
    "19008": "Manufacture of special purpose machinery",
    "19009": "Manufacture of weapons and ammunition",
    "19010": "Manufacture of domestic appliances",
    "19011": "Manufacture of machinery for food, beverage and tobacco processing",
    "19012": "Manufacture of motor vehicles, trailers and semi-trailers",
    "19013": "Manufacture of other transport equipment n.e.c",
    "19014": "Manufacture of medical and surgical equipment and orthopedic appliances",
    "19015": "Manufacture of optical instruments and photographic equipment",
    "19016": "Manufacture of watches and clocks",
    "19017": "Manufacture of other manufacturing n.e.c",
    "20001": "Wholesale of agricultural raw materials and live animals",
    "20002": "Wholesale of food, beverages and tobacco",
    "20003": "Wholesale of textiles, clothing and footwear",
    "20004": "Wholesale of other household goods",
    "20005": "Wholesale of machinery, equipment and supplies",
    "20006": "Wholesale of other intermediate products",
    "20007": "Wholesale of waste and scrap and other products n.e.c",
    "20008": "Wholesale of construction materials, hardware, plumbing and heating equipment and supplies",
    "20009": "Wholesale of chemical products",
    "20010": "Wholesale of metals and metal ores",
    "20011": "Wholesale of wood, construction materials and sanitary equipment",
    "20012": "Wholesale of hardware, plumbing and heating equipment and supplies",
    "20013": "Wholesale of electronic and telecommunications equipment and parts",
    "20014": "Wholesale of agricultural machinery, equipment and supplies",
    "20015": "Wholesale of other machinery and equipment",
    "20016": "Wholesale of solid, liquid and gaseous fuels and related products",
    "20017": "Wholesale on a fee or contract basis",
    "20018": "Wholesale trade of motor vehicle parts and accessories",
    "20019": "Wholesale trade of motor vehicles",
    "20020": "Other wholesale",
    "21001": "Retail sale of automotive fuel",
    "21002": "Retail sale of food, beverages and tobacco in specialized stores",
    "21003": "Retail sale of pharmaceutical and medical goods, cosmetic and toilet articles",
    "21004": "Retail sale of textiles, clothing, footwear and leather goods",
    "21005": "Retail sale of furniture, lighting equipment and other household articles",
    "21006": "Retail sale of hardware, paints and glass",
    "21007": "Retail sale of books, newspapers and stationary",
    "21008": "Retail sale of music and video recordings, sporting equipment, games and toys",
    "21009": "Retail sale of cultural and recreational goods in specialized stores",
    "21010": "Retail sale of information and communication equipment in specialized stores",
    "21011": "Retail sale of other household equipment in specialized stores",
    "21012": "Retail sale of electrical household appliances, furniture, lighting equipment and other household articles n.e.c",
    "21013": "Retail sale of computers, peripheral units, software and telecommunications equipment in specialized stores",
    "21014": "Retail sale of telecommunications equipment",
    "21015": "Retail sale of audio and video equipment",
    "21016": "Retail sale of watches, clocks and jewellery",
    "21017": "Retail sale of flowers, plants, seeds, fertilizers, pet animals and pet food",
    "21018": "Retail sale of games and toys",
    "21019": "Retail sale of newspapers and stationery",
    "21020": "Other retail sale of new goods in specialized stores",
    "21021": "Retail sale of clothing, footwear and leather articles in specialized stores",
    "21022": "Retail sale of pharmaceutical, medical goods and cosmetic and toilet articles",
    "21023": "Retail sale of hardware, paints and glass in specialized stores",
    "21024": "Retail sale of second-hand goods",
    "21025": "Retail sale of antiques including antique books, in stores",
    "21026": "Retail sale of automotive fuel in specialized stores",
    "21027": "Retail sale of computers, peripheral units, software and telecommunications equipment in specialized stores",
    "21028": "Retail sale of electrical household appliances, furniture, lighting equipment and other household articles n.e.c",
    "21029": "Retail sale of audio and video equipment in specialized stores",
    "21030": "Retail sale of music and video recordings in specialized stores",
    "21031": "Retail sale of sports goods",
    "21032": "Retail sale of flowers, plants, seeds, fertilizers, pet animals and pet food in specialized stores",
    "21033": "Retail sale of watches, clocks and jewellery in specialized stores",
    "21034": "Other retail sale not in stores",
    "22001": "Accommodation",
    "22002": "Camping grounds, recreational vehicle parks and trailer parks",
    "22003": "Short term accommodation activities",
    "22004": "Accommodation in hotels, lodges, inns, motels, resorts etc.",
    "22005": "Accommodation in guesthouses, time share units, vacation homes, bed and breakfast establishments etc.",
    "22006": "Accommodation in youth hostels, inns and other lodging places providing rooms",
    "22007": "Other accommodation",
    "23001": "Catering services for the general public",
    "23002": "Catering services for outdoor events",
    "23003": "Other food service activities",
    "23004": "Operation of canteens, cafeterias and snack bars",
    "23005": "Operation of food stalls at mobile markets",
    "23006": "Operation of food courts and other food service activities",
    "24001": "Motion picture projection activities",
    "24002": "Photographic activities",
    "24003": "Activities of sports clubs",
    "24004": "Other entertainment activities",
    "24005": "Operation of sports facilities",
    "24006": "Operation of recreational parks, beaches, public swimming pools and other outdoor recreational facilities",
    "24007": "Operation of amusement parks and theme parks",
    "24008": "Operation of historical sites and buildings and similar visitor attractions",
    "24009": "Botanical and zoological gardens and nature reserve activities",
    "24010": "Museum activities",
    "24011": "Other amusement and recreation activities",
    "25001": "Activities of business and employers organizations",
    "25002": "Activities of professional membership organizations",
    "25003": "Activities of religious organizations",
    "25004": "Activities of political organizations",
    "25005": "Activities of trade unions",
    "25006": "Activities of other membership organizations n.e.c",
    "26001": "Renting and leasing of recreational and sports goods",
    "26002": "Renting and leasing of transport equipment",
    "26003": "Renting and leasing of agricultural machinery and equipment",
    "26004": "Renting and leasing of construction and civil engineering machinery and equipment",
    "26005": "Renting and leasing of office machinery and equipment",
    "26006": "Renting and leasing of other machinery, equipment and tangible goods n.e.c",
    "26007": "Renting and leasing of personal and household goods",
    "26008": "Renting and leasing of recreational and sports goods",
    "26009": "Renting and leasing of transport equipment",
    "26010": "Renting and leasing of agricultural machinery and equipment",
    "26011": "Renting and leasing of construction and civil engineering machinery and equipment",
    "26012": "Renting and leasing of office machinery and equipment",
    "26013": "Renting and leasing of other machinery, equipment and tangible goods n.e.c",
    "27001": "Administration of financial markets",
    "27002": "Security and commodity contracts brokerage",
    "27003": "Security dealing activities",
    "27004": "Fund management activities",
    "27005": "Activities of venture and development capital companies",
    "27006": "Activities auxiliary to financial intermediation n.e.c",
    "28001": "Insurance, reinsurance and pension funding, except compulsory social security",
    "28002": "Life insurance",
    "28003": "Non-life insurance",
    "28004": "Reinsurance",
    "28005": "Pension funding",
    "28006": "Activities auxiliary to insurance and pension funding",
    "29001": "Renting and leasing of real estate",
    "29002": "Real estate activities with own or leased property",
    "30001": "Purchasing of electricity from generation plants and selling it to final consumers",
    "30002": "Purchasing of gas from producers and selling it to final consumers",
    "30003": "Purchasing of water from distribution networks and selling it to final consumers",
    "30004": "Purchasing of steam and hot water from other sources and selling it to final consumers",
    "30005": "Trade of electricity",
    "30006": "Trade of gas through mains",
    "30007": "Trade of steam and hot water",
    "30008": "Trade of water through mains",
    "31001": "Collection and treatment of waste water",
    "31002": "Collection, treatment and disposal of solid waste",
    "31003": "Materials recovery (recycling)",
    "32001": "Repair of fabricated metal products",
    "32002": "Repair of machinery and equipment",
    "32003": "Repair of electrical equipment",
    "32004": "Repair of electronic and optical equipment",
    "32005": "Repair of transport equipment except motor vehicles",
    "32006": "Repair of motor vehicles",
    "32007": "Repair of furniture and home furnishings",
    "32008": "Repair of other goods",
    "33001": "Installation of electrical wiring and fittings",
    "33002": "Plumbing and other construction installation activities",
    "33003": "Heat and air conditioning installation activities",
    "33004": "Building completion and finishing",
    "33005": "Other specialized construction activities",
    "33006": "Manufacture of cement, lime and plaster",
    "33007": "Manufacture of articles of concrete, cement and plaster",
    "33008": "Manufacture of articles of concrete, cement and plaster",
    "33009": "Manufacture of bricks, tiles and construction products of baked clay",
    "33010": "Manufacture of other non-metallic mineral products n.e.c",
    "33011": "Manufacture of other non-metallic mineral products n.e.c",
    "33012": "Manufacture of other non-metallic mineral products n.e.c",
    "33013": "Manufacture of other non-metallic mineral products n.e.c",
    "33014": "Manufacture of other non-metallic mineral products n.e.c",
    "33015": "Manufacture of other non-metallic mineral products n.e.c",
    "33016": "Manufacture of other non-metallic mineral products n.e.c",
    "33017": "Manufacture of other non-metallic mineral products n.e.c",
    "33018": "Manufacture of other non-metallic mineral products n.e.c",
    "33019": "Manufacture of other non-metallic mineral products n.e.c",
    "33020": "Manufacture of other non-metallic mineral products n.e.c",
    "33021": "Manufacture of other non-metallic mineral products n.e.c",
    "33022": "Manufacture of other non-metallic mineral products n.e.c",
    "33023": "Manufacture of other non-metallic mineral products n.e.c",
    "33024": "Manufacture of other non-metallic mineral products n.e.c",
    "33025": "Manufacture of other non-metallic mineral products n.e.c",
    "33026": "Manufacture of other non-metallic mineral products n.e.c",
    "33027": "Manufacture of other non-metallic mineral products n.e.c",
    "33028": "Manufacture of other non-metallic mineral products n.e.c",
    "33029": "Manufacture of other non-metallic mineral products n.e.c",
    "33030": "Manufacture of other non-metallic mineral products n.e.c",
    "33031": "Manufacture of other non-metallic mineral products n.e.c",
    "33032": "Manufacture of other non-metallic mineral products n.e.c",
    "33033": "Manufacture of other non-metallic mineral products n.e.c",
    "33034": "Manufacture of other non-metallic mineral products n.e.c",
    "33035": "Manufacture of other non-metallic mineral products n.e.c",
    "33036": "Manufacture of other non-metallic mineral products n.e.c",
    "33037": "Manufacture of other non-metallic mineral products n.e.c",
    "33038": "Manufacture of other non-metallic mineral products n.e.c",
    "33039": "Manufacture of other non-metallic mineral products n.e.c",
    "33040": "Manufacture of other non-metallic mineral products n.e.c",
    "33041": "Manufacture of other non-metallic mineral products n.e.c",
    "33042": "Manufacture of other non-metallic mineral products n.e.c",
    "33043": "Manufacture of other non-metallic mineral products n.e.c",
    "33044": "Manufacture of other non-metallic mineral products n.e.c",
    "33045": "Manufacture of other non-metallic mineral products n.e.c",
    "33046": "Manufacture of other non-metallic mineral products n.e.c",
    "33047": "Manufacture of other non-metallic mineral products n.e.c",
    "33048": "Manufacture of other non-metallic mineral products n.e.c",
    "33049": "Manufacture of other non-metallic mineral products n.e.c",
    "33050": "Manufacture of other non-metallic mineral products n.e.c",
    "33051": "Manufacture of other non-metallic mineral products n.e.c",
    "33052": "Manufacture of other non-metallic mineral products n.e.c",
    "33053": "Manufacture of other non-metallic mineral products n.e.c",
    "33054": "Manufacture of other non-metallic mineral products n.e.c",
    "33055": "Manufacture of other non-metallic mineral products n.e.c",
    "33056": "Manufacture of other non-metallic mineral products n.e.c",
    "33057": "Manufacture of other non-metallic mineral products n.e.c",
    "33058": "Manufacture of other non-metallic mineral products n.e.c",
    "33059": "Manufacture of other non-metallic mineral products n.e.c",
    "33060": "Manufacture of other non-metallic mineral products n.e.c",
    "33061": "Manufacture of other non-metallic mineral products n.e.c",
    "33062": "Manufacture of other non-metallic mineral products n.e.c",
    "33063": "Manufacture of other non-metallic mineral products n.e.c",
    "33064": "Manufacture of other non-metallic mineral products n.e.c",
    "33065": "Manufacture of other non-metallic mineral products n.e.c",
    "33066": "Manufacture of other non-metallic mineral products n.e.c",
    "33067": "Manufacture of other non-metallic mineral products n.e.c",
    "33068": "Manufacture of other non-metallic mineral products n.e.c",
    "33069": "Manufacture of other non-metallic mineral products n.e.c",
    "33070": "Manufacture of other non-metallic mineral products n.e.c",
    "33071": "Manufacture of other non-metallic mineral products n.e.c",
    "33072": "Manufacture of other non-metallic mineral products n.e.c",
    "33073": "Manufacture of other non-metallic mineral products n.e.c",
    "33074": "Manufacture of other non-metallic mineral products n.e.c",
    "33075": "Manufacture of other non-metallic mineral products n.e.c",
    "33076": "Manufacture of other non-metallic mineral products n.e.c",
    "33077": "Manufacture of other non-metallic mineral products n.e.c",
    "33078": "Manufacture of other non-metallic mineral products n.e.c",
    "33079": "Manufacture of other non-metallic mineral products n.e.c",
    "33080": "Manufacture of other non-metallic mineral products n.e.c",
    "33081": "Manufacture of other non-metallic mineral products n.e.c",
    "33082": "Manufacture of other non-metallic mineral products n.e.c",
    "33083": "Manufacture of other non-metallic mineral products n.e.c",
    "33084": "Manufacture of other non-metallic mineral products n.e.c",
    "33085": "Manufacture of other non-metallic mineral products n.e.c",
    "33086": "Manufacture of other non-metallic mineral products n.e.c",
    "33087": "Manufacture of other non-metallic mineral products n.e.c",
    "33088": "Manufacture of other non-metallic mineral products n.e.c",
    "33089": "Manufacture of other non-metallic mineral products n.e.c",
    "33090": "Manufacture of other non-metallic mineral products n.e.c",
    "33091": "Manufacture of other non-metallic mineral products n.e.c",
    "33092": "Manufacture of other non-metallic mineral products n.e.c",
    "33093": "Manufacture of other non-metallic mineral products n.e.c",
    "33094": "Manufacture of other non-metallic mineral products n.e.c",
    "33095": "Manufacture of other non-metallic mineral products n.e.c",
    "33096": "Manufacture of other non-metallic mineral products n.e.c",
    "33097": "Manufacture of other non-metallic mineral products n.e.c",
    "33098": "Manufacture of other non-metallic mineral products n.e.c",
    "33099": "Manufacture of other non-metallic mineral products n.e.c",
    "33100": "Manufacture of other non-metallic mineral products n.e.c",
    "33101": "Manufacture of other non-metallic mineral products n.e.c",
    "33102": "Manufacture of other non-metallic mineral products n.e.c",
    "33103": "Manufacture of other non-metallic mineral products n.e.c",
    "33104": "Manufacture of other non-metallic mineral products n.e.c",
    "33105": "Manufacture of other non-metallic mineral products n.e.c",
    "33106": "Manufacture of other non-metallic mineral products n.e.c",
    "33107": "Manufacture of other non-metallic mineral products n.e.c",
    "33108": "Manufacture of other non-metallic mineral products n.e.c",
    "33109": "Manufacture of other non-metallic mineral products n.e.c",
    "33110": "Manufacture of other non-metallic mineral products n.e.c",
    "33111": "Manufacture of other non-metallic mineral products n.e.c",
    "33112": "Manufacture of other non-metallic mineral products n.e.c",
    "33113": "Manufacture of other non-metallic mineral products n.e.c",
    "33114": "Manufacture of other non-metallic mineral products n.e.c",
    "33115": "Manufacture of other non-metallic mineral products n.e.c",
    "33116": "Manufacture of other non-metallic mineral products n.e.c",
    "33117": "Manufacture of other non-metallic mineral products n.e.c",
    "33118": "Manufacture of other non-metallic mineral products n.e.c",
    "33119": "Manufacture of other non-metallic mineral products n.e.c",
    "33120": "Manufacture of other non-metallic mineral products n.e.c",
    "33121": "Manufacture of other non-metallic mineral products n.e.c",
    "33122": "Manufacture of other non-metallic mineral products n.e.c",
    "33123": "Manufacture of other non-metallic mineral products n.e.c",
    "33124": "Manufacture of other non-metallic mineral products n.e.c",
    "33125": "Manufacture of other non-metallic mineral products n.e.c",
    "33126": "Manufacture of other non-metallic mineral products n.e.c",
    "33127": "Manufacture of other non-metallic mineral products n.e.c",
    "33128": "Manufacture of other non-metallic mineral products n.e.c",
    "33129": "Manufacture of other non-metallic mineral products n.e.c",
    "33130": "Manufacture of other non-metallic mineral products n.e.c",
    "33131": "Manufacture of other non-metallic mineral products n.e.c",
    "33132": "Manufacture of other non-metallic mineral products n.e.c",
    "33133": "Manufacture of other non-metallic mineral products n.e.c",
    "33134": "Manufacture of other non-metallic mineral products n.e.c",
    "33135": "Manufacture of other non-metallic mineral products n.e.c",
    "33136": "Manufacture of other non-metallic mineral products n.e.c",
    "33137": "Manufacture of other non-metallic mineral products n.e.c",
    "33138": "Manufacture of other non-metallic mineral products n.e.c",
    "33139": "Manufacture of other non-metallic mineral products n.e.c",
    "33140": "Manufacture of other non-metallic mineral products n.e.c",
    "33141": "Manufacture of other non-metallic mineral products n.e.c",
    "33142": "Manufacture of other non-metallic mineral products n.e.c",
    "33143": "Manufacture of other non-metallic mineral products n.e.c",
    "33144": "Manufacture of other non-metallic mineral products n.e.c",
    "33145": "Manufacture of other non-metallic mineral products n.e.c",
    "33146": "Manufacture of other non-metallic mineral products n.e.c",
    "33147": "Manufacture of other non-metallic mineral products n.e.c",
    "33148": "Manufacture of other non-metallic mineral products n.e.c",
    "33149": "Manufacture of other non-metallic mineral products n.e.c",
    "33150": "Manufacture of other non-metallic mineral products n.e.c",
    "33151": "Manufacture of other non-metallic mineral products n.e.c",
    "33152": "Manufacture of other non-metallic mineral products n.e.c",
    "33153": "Manufacture of other non-metallic mineral products n.e.c",
    "33154": "Manufacture of other non-metallic mineral products n.e.c",
    "33155": "Manufacture of other non-metallic mineral products n.e.c",
    "33156": "Manufacture of other non-metallic mineral products n.e.c",
    "33157": "Manufacture of other non-metallic mineral products n.e.c",
    "33158": "Manufacture of other non-metallic mineral products n.e.c",
    "33159": "Manufacture of other non-metallic mineral products n.e.c",
    "33160": "Manufacture of other non-metallic mineral products n.e.c",
    "33161": "Manufacture of other non-metallic mineral products n.e.c",
    "33162": "Manufacture of other non-metallic mineral products n.e.c",
    "33163": "Manufacture of other non-metallic mineral products n.e.c",
    "33164": "Manufacture of other non-metallic mineral products n.e.c",
    "33165": "Manufacture of other non-metallic mineral products n.e.c",
    "33166": "Manufacture of other non-metallic mineral products n.e.c",
    "33167": "Manufacture of other non-metallic mineral products n.e.c",
    "33168": "Manufacture of other non-metallic mineral products n.e.c",
    "33169": "Manufacture of other non-metallic mineral products n.e.c",
    "33170": "Manufacture of other non-metallic mineral products n.e.c",
    "33171": "Manufacture of other non-metallic mineral products n.e.c",
    "33172": "Manufacture of other non-metallic mineral products n.e.c",
    "33173": "Manufacture of other non-metallic mineral products n.e.c",
    "33174": "Manufacture of other non-metallic mineral products n.e.c",
    "33175": "Manufacture of other non-metallic mineral products n.e.c",
    "33176": "Manufacture of other non-metallic mineral products n.e.c",
    "33177": "Manufacture of other non-metallic mineral products n.e.c",
    "33178": "Manufacture of other non-metallic mineral products n.e.c",
    "33179": "Manufacture of other non-metallic mineral products n.e.c",
    "33180": "Manufacture of other non-metallic mineral products n.e.c",
    "33181": "Manufacture of other non-metallic mineral products n.e.c",
    "33182": "Manufacture of other non-metallic mineral products n.e.c",
    "33183": "Manufacture of other non-metallic mineral products n.e.c",
    "33184": "Manufacture of other non-metallic mineral products n.e.c",
    "33185": "Manufacture of other non-metallic mineral products n.e.c",
    "33186": "Manufacture of other non-metallic mineral products n.e.c",
    "33187": "Manufacture of other non-metallic mineral products n.e.c",
    "33188": "Manufacture of other non-metallic mineral products n.e.c",
    "33189": "Manufacture of other non-metallic mineral products n.e.c",
    "33190": "Manufacture of other non-metallic mineral products n.e.c",
    "33191": "Manufacture of other non-metallic mineral products n.e.c",
    "33192": "Manufacture of other non-metallic mineral products n.e.c",
    "33193": "Manufacture of other non-metallic mineral products n.e.c",
    "33194": "Manufacture of other non-metallic mineral products n.e.c",
    "33195": "Manufacture of other non-metallic mineral products n.e.c",
    "33196": "Manufacture of other non-metallic mineral products n.e.c",
    "33197": "Manufacture of other non-metallic mineral products n.e.c",
    "33198": "Manufacture of other non-metallic mineral products n.e.c",
    "33199": "Manufacture of other non-metallic mineral products n.e.c",
    "33200": "Manufacture of other non-metallic mineral products n.e.c",
    "33201": "Manufacture of other non-metallic mineral products n.e.c",
    "33202": "Manufacture of other non-metallic mineral products n.e.c",
    "33203": "Manufacture of other non-metallic mineral products n.e.c",
    "33204": "Manufacture of other non-metallic mineral products n.e.c",
    "33205": "Manufacture of other non-metallic mineral products n.e.c",
    "33206": "Manufacture of other non-metallic mineral products n.e.c",
    "33207": "Manufacture of other non-metallic mineral products n.e.c",
    "33208": "Manufacture of other non-metallic mineral products n.e.c",
    "33209": "Manufacture of other non-metallic mineral products n.e.c",
    "33210": "Manufacture of other non-metallic mineral products n.e.c",
    "33211": "Manufacture of other non-metallic mineral products n.e.c",
    "33212": "Manufacture of other non-metallic mineral products n.e.c",
    "33213": "Manufacture of other non-metallic mineral products n.e.c",
    "33214": "Manufacture of other non-metallic mineral products n.e.c",
    "33215": "Manufacture of other non-metallic mineral products n.e.c",
    "33216": "Manufacture of other non-metallic mineral products n.e.c",
    "33217": "Manufacture of other non-metallic mineral products n.e.c",
    "33218": "Manufacture of other non-metallic mineral products n.e.c",
    "33219": "Manufacture of other non-metallic mineral products n.e.c",
    "33220": "Manufacture of other non-metallic mineral products n.e.c",
    "33221": "Manufacture of other non-metallic mineral products n.e.c",
    "33222": "Manufacture of other non-metallic mineral products n.e.c",
    "33223": "Manufacture of other non-metallic mineral products n.e.c",
    "33224": "Manufacture of other non-metallic mineral products n.e.c",
    "33225": "Manufacture of other non-metallic mineral products n.e.c",
    "33226": "Manufacture of other non-metallic mineral products n.e.c",
    "33227": "Manufacture of other non-metallic mineral products n.e.c",
    "33228": "Manufacture of other non-metallic mineral products n.e.c",
    "33229": "Manufacture of other non-metallic mineral products n.e.c",
    "33230": "Manufacture of other non-metallic mineral products n.e.c",
    "33231": "Manufacture of other non-metallic mineral products n.e.c",
    "33232": "Manufacture of other non-metallic mineral products n.e.c",
    "33233": "Manufacture of other non-metallic mineral products n.e.c",
    "33234": "Manufacture of other non-metallic mineral products n.e.c",
    "33235": "Manufacture of other non-metallic mineral products n.e.c",
    "33236": "Manufacture of other non-metallic mineral products n.e.c",
    "33237": "Manufacture of other non-metallic mineral products n.e.c",
    "33238": "Manufacture of other non-metallic mineral products n.e.c",
    "33239": "Manufacture of other non-metallic mineral products n.e.c",
    "33240": "Manufacture of other non-metallic mineral products n.e.c",
    "33241": "Manufacture of other non-metallic mineral products n.e.c",
    "33242": "Manufacture of other non-metallic mineral products n.e.c",
    "33243": "Manufacture of other non-metallic mineral products n.e.c",
    "33244": "Manufacture of other non-metallic mineral products n.e.c",
    "33245": "Manufacture of other non-metallic mineral products n.e.c",
    "33246": "Manufacture of other non-metallic mineral products n.e.c",
    "33247": "Manufacture of other non-metallic mineral products n.e.c",
    "33248": "Manufacture of other non-metallic mineral products n.e.c",
    "33249": "Manufacture of other non-metallic mineral products n.e.c",
    "33250": "Manufacture of other non-metallic mineral products n.e.c",
    "33251": "Manufacture of other non-metallic mineral products n.e.c",
    "33252": "Manufacture of other non-metallic mineral products n.e.c",
    "33253": "Manufacture of other non-metallic mineral products n.e.c",
    "33254": "Manufacture of other non-metallic mineral products n.e.c",
    "33255": "Manufacture of other non-metallic mineral products n.e.c",
    "33256": "Manufacture of other non-metallic mineral products n.e.c",
    "33257": "Manufacture of other non-metallic mineral products n.e.c",
    "33258": "Manufacture of other non-metallic mineral products n.e.c",
    "33259": "Manufacture of other non-metallic mineral products n.e.c",
    "33260": "Manufacture of other non-metallic mineral products n.e.c",
    "33261": "Manufacture of other non-metallic mineral products n.e.c",
    "33262": "Manufacture of other non-metallic mineral products n.e.c",
    "33263": "Manufacture of other non-metallic mineral products n.e.c",
    "33264": "Manufacture of other non-metallic mineral products n.e.c",
    "33265": "Manufacture of other non-metallic mineral products n.e.c",
    "33266": "Manufacture of other non-metallic mineral products n.e.c",
    "33267": "Manufacture of other non-metallic mineral products n.e.c",
    "33268": "Manufacture of other non-metallic mineral products n.e.c",
    "33269": "Manufacture of other non-metallic mineral products n.e.c",
    "33270": "Manufacture of other non-metallic mineral products n.e.c",
    "33271": "Manufacture of other non-metallic mineral products n.e.c",
    "33272": "Manufacture of other non-metallic mineral products n.e.c",
    "33273": "Manufacture of other non-metallic mineral products n.e.c",
    "33274": "Manufacture of other non-metallic mineral products n.e.c",
    "33275": "Manufacture of other non-metallic mineral products n.e.c",
    "33276": "Manufacture of other non-metallic mineral products n.e.c",
    "33277": "Manufacture of other non-metallic mineral products n.e.c",
    "33278": "Manufacture of other non-metallic mineral products n.e.c",
    "33279": "Manufacture of other non-metallic mineral products n.e.c",
    "33280": "Manufacture of other non-metallic mineral products n.e.c",
    "33281": "Manufacture of other non-metallic mineral products n.e.c",
    "33282": "Manufacture of other non-metallic mineral products n.e.c",
    "33283": "Manufacture of other non-metallic mineral products n.e.c",
    "33284": "Manufacture of other non-metallic mineral products n.e.c",
    "33285": "Manufacture of other non-metallic mineral products n.e.c",
    "33286": "Manufacture of other non-metallic mineral products n.e.c",
    "33287": "Manufacture of other non-metallic mineral products n.e.c",
    "33288": "Manufacture of other non-metallic mineral products n.e.c",
    "33289": "Manufacture of other non-metallic mineral products n.e.c",
    "33290": "Manufacture of other non-metallic mineral products n.e.c",
    "33291": "Manufacture of other non-metallic mineral products n.e.c",
    "33292": "Manufacture of other non-metallic mineral products n.e.c",
    "33293": "Manufacture of other non-metallic mineral products n.e.c",
    "33294": "Manufacture of other non-metallic mineral products n.e.c",
    "33295": "Manufacture of other non-metallic mineral products n.e.c",
    "33296": "Manufacture of other non-metallic mineral products n.e.c",
    "33297": "Manufacture of other non-metallic mineral products n.e.c",
    "33298": "Manufacture of other non-metallic mineral products n.e.c",
    "33299": "Manufacture of other non-metallic mineral products n.e.c",
    "33300": "Manufacture of other non-metallic mineral products n.e.c",
    "33301": "Manufacture of other non-metallic mineral products n.e.c",
    "33302": "Manufacture of other non-metallic mineral products n.e.c",
    "33303": "Manufacture of other non-metallic mineral products n.e.c",
    "33304": "Manufacture of other non-metallic mineral products n.e.c",
    "33305": "Manufacture of other non-metallic mineral products n.e.c",
    "33306": "Manufacture of other non-metallic mineral products n.e.c",
    "33307": "Manufacture of other non-metallic mineral products n.e.c",
    "33308": "Manufacture of other non-metallic mineral products n.e.c",
    "33309": "Manufacture of other non-metallic mineral products n.e.c",
    "33310": "Manufacture of other non-metallic mineral products n.e.c",
    "33311": "Manufacture of other non-metallic mineral products n.e.c",
    "33312": "Manufacture of other non-metallic mineral products n.e.c",
    "33313": "Manufacture of other non-metallic mineral products n.e.c",
    "33314": "Manufacture of other non-metallic mineral products n.e.c",
    "33315": "Manufacture of other non-metallic mineral products n.e.c",
    "33316": "Manufacture of other non-metallic mineral products n.e.c",
    "33317": "Manufacture of other non-metallic mineral products n.e.c",
    "33318": "Manufacture of other non-metallic mineral products n.e.c",
    "33319": "Manufacture of other non-metallic mineral products n.e.c",
    "33320": "Manufacture of other non-metallic mineral products n.e.c",
    "33321": "Manufacture of other non-metallic mineral products n.e.c",
    "33322": "Manufacture of other non-metallic mineral products n.e.c",
    "33323": "Manufacture of other non-metallic mineral products n.e.c",
    "33324": "Manufacture of other non-metallic mineral products n.e.c",
    "33325": "Manufacture of other non-metallic mineral products n.e.c",
    "33326": "Manufacture of other non-metallic mineral products n.e.c",
    "33327": "Manufacture of other non-metallic mineral products n.e.c",
    "33328": "Manufacture of other non-metallic mineral products n.e.c",
    "33329": "Manufacture of other non-metallic mineral products n.e.c",
    "33330": "Manufacture of other non-metallic mineral products n.e.c",
    "33331": "Manufacture of other non-metallic mineral products n.e.c",
    "33332": "Manufacture of other non-metallic mineral products n.e.c",
    "33333": "Manufacture of other non-metallic mineral products n.e.c",
    "33334": "Manufacture of other non-metallic mineral products n.e.c",
    "33335": "Manufacture of other non-metallic mineral products n.e.c",
    "33336": "Manufacture of other non-metallic mineral products n.e.c",
    "33337": "Manufacture of other non-metallic mineral products n.e.c",
    "33338": "Manufacture of other non-metallic mineral products n.e.c",
    "33339": "Manufacture of other non-metallic mineral products n.e.c",
    "33340": "Manufacture of other non-metallic mineral products n.e.c",
    "33341": "Manufacture of other non-metallic mineral products n.e.c",
    "33342": "Manufacture of other non-metallic mineral products n.e.c",
    "33343": "Manufacture of other non-metallic mineral products n.e.c",
    "33344": "Manufacture of other non-metallic mineral products n.e.c",
    "33345": "Manufacture of other non-metallic mineral products n.e.c",
    "33346": "Manufacture of other non-metallic mineral products n.e.c",
    "33347": "Manufacture of other non-metallic mineral products n.e.c",
    "33348": "Manufacture of other non-metallic mineral products n.e.c",
    "33349": "Manufacture of other non-metallic mineral products n.e.c",
    "33350": "Manufacture of other non-metallic mineral products n.e.c",
    "33351": "Manufacture of other non-metallic mineral products n.e.c",
    "33352": "Manufacture of other non-metallic mineral products n.e.c",
    "33353": "Manufacture of other non-metallic mineral products n.e.c",
    "33354": "Manufacture of other non-metallic mineral products n.e.c",
    "33355": "Manufacture of other non-metallic mineral products n.e.c",
    "33356": "Manufacture of other non-metallic mineral products n.e.c",
    "33357": "Manufacture of other non-metallic mineral products n.e.c",
    "33358": "Manufacture of other non-metallic mineral products n.e.c",
    "33359": "Manufacture of other non-metallic mineral products n.e.c",
    "33360": "Manufacture of other non-metallic mineral products n.e.c",
    "33361": "Manufacture of other non-metallic mineral products n.e.c",
    "33362": "Manufacture of other non-metallic mineral products n.e.c",
    "33363": "Manufacture of other non-metallic mineral products n.e.c",
    "33364": "Manufacture of other non-metallic mineral products n.e.c",
    "33365": "Manufacture of other non-metallic mineral products n.e.c",
    "33366": "Manufacture of other non-metallic mineral products n.e.c",
    "33367": "Manufacture of other non-metallic mineral products n.e.c",
    "33368": "Manufacture of other non-metallic mineral products n.e.c",
    "33369": "Manufacture of other non-metallic mineral products n.e.c",
    "33370": "Manufacture of other non-metallic mineral products n.e.c",
    "33371": "Manufacture of other non-metallic mineral products n.e.c",
    "33372": "Manufacture of other non-metallic mineral products n.e.c",
    "33373": "Manufacture of other non-metallic mineral products n.e.c",
    "33374": "Manufacture of other non-metallic mineral products n.e.c",
    "33375": "Manufacture of other non-metallic mineral products n.e.c",
    "33376": "Manufacture of other non-metallic mineral products n.e.c",
    "33377": "Manufacture of other non-metallic mineral products n.e.c",
    "33378": "Manufacture of other non-metallic mineral products n.e.c",
    "33379": "Manufacture of other non-metallic mineral products n.e.c",
    "33380": "Manufacture of other non-metallic mineral products n.e.c",
    "33381": "Manufacture of other non-metallic mineral products n.e.c",
    "33382": "Manufacture of other non-metallic mineral products n.e.c",
    "33383": "Manufacture of other non-metallic mineral products n.e.c",
    "33384": "Manufacture of other non-metallic mineral products n.e.c",
    "33385": "Manufacture of other non-metallic mineral products n.e.c",
    "33386": "Manufacture of other non-metallic mineral products n.e.c",
    "33387": "Manufacture of other non-metallic mineral products n.e.c",
    "33388": "Manufacture of other non-metallic mineral products n.e.c",
    "33389": "Manufacture of other non-metallic mineral products n.e.c",
    "33390": "Manufacture of other non-metallic mineral products n.e.c",
    "33391": "Manufacture of other non-metallic mineral products n.e.c",
    "33392": "Manufacture of other non-metallic mineral products n.e.c",
    "33393": "Manufacture of other non-metallic mineral products n.e.c",
    "33394": "Manufacture of other non-metallic mineral products n.e.c",
    "33395": "Manufacture of other non-metallic mineral products n.e.c",
    "33396": "Manufacture of other non-metallic mineral products n.e.c",
    "33397": "Manufacture of other non-metallic mineral products n.e.c",
    "33398": "Manufacture of other non-metallic mineral products n.e.c",
    "33399": "Manufacture of other non-metallic mineral products n.e.c",
    "33400": "Manufacture of other non-metallic mineral products n.e.c",
    "33401": "Manufacture of other non-metallic mineral products n.e.c",
    "33402": "Manufacture of other non-metallic mineral products n.e.c",
    "33403": "Manufacture of other non-metallic mineral products n.e.c",
    "33404": "Manufacture of other non-metallic mineral products n.e.c",
    "33405": "Manufacture of other non-metallic mineral products n.e.c",
    "33406": "Manufacture of other non-metallic mineral products n.e.c",
    "33407": "Manufacture of other non-metallic mineral products n.e.c",
    "33408": "Manufacture of other non-metallic mineral products n.e.c",
    "33409": "Manufacture of other non-metallic mineral products n.e.c",
    "33410": "Manufacture of other non-metallic mineral products n.e.c",
    "33411": "Manufacture of other non-metallic mineral products n.e.c",
    "33412": "Manufacture of other non-metallic mineral products n.e.c",
    "33413": "Manufacture of other non-metallic mineral products n.e.c",
    "33414": "Manufacture of other non-metallic mineral products n.e.c",
    "33415": "Manufacture of other non-metallic mineral products n.e.c",
    "33416": "Manufacture of other non-metallic mineral products n.e.c",
    "33417": "Manufacture of other non-metallic mineral products n.e.c",
    "33418": "Manufacture of other non-metallic mineral products n.e.c",
    "33419": "Manufacture of other non-metallic mineral products n.e.c",
    "33420": "Manufacture of other non-metallic mineral products n.e.c",
    "33421": "Manufacture of other non-metallic mineral products n.e.c",
    "33422": "Manufacture of other non-metallic mineral products n.e.c",
    "33423": "Manufacture of other non-metallic mineral products n.e.c",
    "33424": "Manufacture of other non-metallic mineral products n.e.c",
    "33425": "Manufacture of other non-metallic mineral products n.e.c",
    "33426": "Manufacture of other non-metallic mineral products n.e.c",
    "33427": "Manufacture of other non-metallic mineral products n.e.c",
    "33428": "Manufacture of other non-metallic mineral products n.e.c",
    "33429": "Manufacture of other non-metallic mineral products n.e.c",
    "33430": "Manufacture of other non-metallic mineral products n.e.c",
    "33431": "Manufacture of other non-metallic mineral products n.e.c",
    "33432": "Manufacture of other non-metallic mineral products n.e.c",
    "33433": "Manufacture of other non-metallic mineral products n.e.c",
    "33434": "Manufacture of other non-metallic mineral products n.e.c",
    "33435": "Manufacture of other non-metallic mineral products n.e.c",
    "33436": "Manufacture of other non-metallic mineral products n.e.c",
    "33437": "Manufacture of other non-metallic mineral products n.e.c",
    "33438": "Manufacture of other non-metallic mineral products n.e.c",
    "33439": "Manufacture of other non-metallic mineral products n.e.c",
    "33440": "Manufacture of other non-metallic mineral products n.e.c",
    "33441": "Manufacture of other non-metallic mineral products n.e.c",
    "33442": "Manufacture of other non-metallic mineral products n.e.c",
    "33443": "Manufacture of other non-metallic mineral products n.e.c",
    "33444": "Manufacture of other non-metallic mineral products n.e.c",
    "33445": "Manufacture of other non-metallic mineral products n.e.c",
    "33446": "Manufacture of other non-metallic mineral products n.e.c",
    "33447": "Manufacture of other non-metallic mineral products n.e.c",
    "33448": "Manufacture of other non-metallic mineral products n.e.c",
    "33449": "Manufacture of other non-metallic mineral products n.e.c",
    "33450": "Manufacture of other non-metallic mineral products n.e.c",
    "33451": "Manufacture of other non-metallic mineral products n.e.c",
    "33452": "Manufacture of other non-metallic mineral products n.e.c",
    "33453": "Manufacture of other non-metallic mineral products n.e.c"
}  